apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  django-secret-key: "django-insecure-u&f*bkkxxjrz)+%_)_e6vu4ui#iv%@_h5&xpedbeu7mv^!p@_7"  # Cambia esto por una clave segura